config/routes.rb
Eplus::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  #root :to => "home#index"
  root :to => redirect("/users/sign_in")
#  devise_for :users
devise_for :users do
  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
end
  resources :users
  resource :users do
  	post 'do_reset_password'
	end
  
  
  resources :nfers
  resources :statuses
  resources :submissions
  resources :religions
  resources :forms
  resources :students
  resources :postcodes
  resources :genders
  resources :dayboards
  resources :curriculums
  resources :counties
  resources :schools
  
  match 'import_nfers' => 'nfers#import', :as => :import_nfers
  match 'import_students' => 'students#import', :as => :import_students
  match 'import_users' => 'users#import', :as => :import_users
  
  match 'data' => 'home#data', :as => :data
  match 'about' =>'home#about', :as => :about
  match "clean_up" => "nfers#clean_up"
  
end

app/models/dayboard.rb
class Dayboard < ActiveRecord::Base
  attr_accessible :name
  has_many :schools

end

app/controllers/dayboards_controller.rb
class DayboardsController < ApplicationController
  # GET /dayboards
  # GET /dayboards.json
  def index
    @dayboards = Dayboard.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dayboards }
    end
  end

  # GET /dayboards/1
  # GET /dayboards/1.json
  def show
    @dayboard = Dayboard.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dayboard }
    end
  end

  # GET /dayboards/new
  # GET /dayboards/new.json
  def new
    @dayboard = Dayboard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dayboard }
    end
  end

  # GET /dayboards/1/edit
  def edit
    @dayboard = Dayboard.find(params[:id])
  end

  # POST /dayboards
  # POST /dayboards.json
  def create
    @dayboard = Dayboard.new(params[:dayboard])

    respond_to do |format|
      if @dayboard.save
        format.html { redirect_to @dayboard, notice: 'Dayboard was successfully created.' }
        format.json { render json: @dayboard, status: :created, location: @dayboard }
      else
        format.html { render action: "new" }
        format.json { render json: @dayboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dayboards/1
  # PUT /dayboards/1.json
  def update
    @dayboard = Dayboard.find(params[:id])

    respond_to do |format|
      if @dayboard.update_attributes(params[:dayboard])
        format.html { redirect_to @dayboard, notice: 'Dayboard was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dayboard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dayboards/1
  # DELETE /dayboards/1.json
  def destroy
    @dayboard = Dayboard.find(params[:id])
    @dayboard.destroy

    respond_to do |format|
      format.html { redirect_to dayboards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dayboards_helper.rb
module DayboardsHelper
end

app/views/dayboards/_form.html.erb
<%= simple_form_for(@dayboard) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/dayboards/edit.html.erb
<h1>Editing dayboard</h1>

<%= render 'form' %>

<%= link_to 'Show', @dayboard %> |
<%= link_to 'Back', dayboards_path %>

app/views/dayboards/index.html.erb
<h1>Listing dayboards</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dayboards.each do |dayboard| %>
  <tr>
    <td><%= dayboard.name %></td>
    <td><%= link_to 'Show', dayboard %></td>
    <td><%= link_to 'Edit', edit_dayboard_path(dayboard) %></td>
    <td><%= link_to 'Destroy', dayboard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dayboard', new_dayboard_path %>

app/views/dayboards/new.html.erb
<h1>New dayboard</h1>

<%= render 'form' %>

<%= link_to 'Back', dayboards_path %>

app/views/dayboards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @dayboard.name %>
</p>


<%= link_to 'Edit', edit_dayboard_path(@dayboard) %> |
<%= link_to 'Back', dayboards_path %>