config/routes.rb
Eplus::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  #root :to => "home#index"
  root :to => redirect("/users/sign_in")
#  devise_for :users
devise_for :users do
  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
end
  resources :users
  resource :users do
  	post 'do_reset_password'
	end
  
  
  resources :nfers
  resources :statuses
  resources :submissions
  resources :religions
  resources :forms
  resources :students
  resources :postcodes
  resources :genders
  resources :dayboards
  resources :curriculums
  resources :counties
  resources :schools
  
  match 'import_nfers' => 'nfers#import', :as => :import_nfers
  match 'import_students' => 'students#import', :as => :import_students
  match 'import_users' => 'users#import', :as => :import_users
  
  match 'data' => 'home#data', :as => :data
  match 'about' =>'home#about', :as => :about
  match "clean_up" => "nfers#clean_up"
  
end

app/models/religion.rb
class Religion < ActiveRecord::Base
  attr_accessible :name
  has_many :schools

end

app/controllers/religions_controller.rb
class ReligionsController < ApplicationController
  # GET /religions
  # GET /religions.json
  def index
    @religions = Religion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @religions }
    end
  end

  # GET /religions/1
  # GET /religions/1.json
  def show
    @religion = Religion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @religion }
    end
  end

  # GET /religions/new
  # GET /religions/new.json
  def new
    @religion = Religion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @religion }
    end
  end

  # GET /religions/1/edit
  def edit
    @religion = Religion.find(params[:id])
  end

  # POST /religions
  # POST /religions.json
  def create
    @religion = Religion.new(params[:religion])

    respond_to do |format|
      if @religion.save
        format.html { redirect_to @religion, notice: 'Religion was successfully created.' }
        format.json { render json: @religion, status: :created, location: @religion }
      else
        format.html { render action: "new" }
        format.json { render json: @religion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /religions/1
  # PUT /religions/1.json
  def update
    @religion = Religion.find(params[:id])

    respond_to do |format|
      if @religion.update_attributes(params[:religion])
        format.html { redirect_to @religion, notice: 'Religion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @religion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /religions/1
  # DELETE /religions/1.json
  def destroy
    @religion = Religion.find(params[:id])
    @religion.destroy

    respond_to do |format|
      format.html { redirect_to religions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/religions_helper.rb
module ReligionsHelper
end

app/views/religions/_form.html.erb
<%= simple_form_for(@religion) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/religions/edit.html.erb
<h1>Editing religion</h1>

<%= render 'form' %>

<%= link_to 'Show', @religion %> |
<%= link_to 'Back', religions_path %>

app/views/religions/index.html.erb
<h1>Listing religions</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @religions.each do |religion| %>
  <tr>
    <td><%= religion.name %></td>
    <td><%= link_to 'Show', religion %></td>
    <td><%= link_to 'Edit', edit_religion_path(religion) %></td>
    <td><%= link_to 'Destroy', religion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Religion', new_religion_path %>

app/views/religions/new.html.erb
<h1>New religion</h1>

<%= render 'form' %>

<%= link_to 'Back', religions_path %>

app/views/religions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @religion.name %>
</p>


<%= link_to 'Edit', edit_religion_path(@religion) %> |
<%= link_to 'Back', religions_path %>