config/routes.rb
Eplus::Application.routes.draw do
  authenticated :user do
    root :to => 'home#index'
  end
  #root :to => "home#index"
  root :to => redirect("/users/sign_in")
#  devise_for :users
devise_for :users do
  get "/users/sign_out" => "devise/sessions#destroy", :as => :destroy_user_session
end
  resources :users
  resource :users do
  	post 'do_reset_password'
	end
  
  
  resources :nfers
  resources :statuses
  resources :submissions
  resources :religions
  resources :forms
  resources :students
  resources :postcodes
  resources :genders
  resources :dayboards
  resources :curriculums
  resources :counties
  resources :schools
  
  match 'import_nfers' => 'nfers#import', :as => :import_nfers
  match 'import_students' => 'students#import', :as => :import_students
  match 'import_users' => 'users#import', :as => :import_users
  
  match 'data' => 'home#data', :as => :data
  match 'about' =>'home#about', :as => :about
  match "clean_up" => "nfers#clean_up"
  
end

app/models/nfer.rb
class Nfer < ActiveRecord::Base
  attr_accessible :raw, :schoolreference, :ss, :student_id, :subject, :date_taken
  
  belongs_to :student
  
private
  #FOR BULK UPLOAD 

    #for bulk upload
    def self.csv_header
        "Name,email".split(',')
    end

    def self.build_from_csv(row)
        # find existing user from email or create new
        n   = Nfer.new
        n.attributes = {
            :subject => row[0],
            :raw => row[1],
            :ss => row[2],
            :schoolreference =>row[3],
            :date_taken => row[4]
        }
    return n 
    end


end

app/controllers/nfers_controller.rb
class NfersController < ApplicationController
  # GET /nfers
  # GET /nfers.json
  def index
    @nfers = Nfer.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nfers }
    end
  end

  # GET /nfers/1
  # GET /nfers/1.json
  def show
    @nfer = Nfer.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nfer }
    end
  end

  # GET /nfers/new
  # GET /nfers/new.json
  def new
    @nfer = Nfer.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nfer }
    end
    #for bulk imports
    #http://www.funonrails.com/2012/01/csv-file-importexport-in-rails-3.html
  end    
    
  def import
     require 'csv'
        if request.post? && params[:file].present?
            infile = params[:file].read
            n, errs = 0, []
            CSV.parse(infile) do |row| n += 1
                # SKIP: header i.e. first row OR blank row
                #                next if n == 1 or row.join.blank?
                # build_from_csv method will map customer attributes &
                # build new customer record
                nfer = Nfer.build_from_csv(row)
                # Save upon valid
                # otherwise collect error records to export
                if nfer.valid?
                    nfer.save
                    else
                    errs << row
                end
            end
            
            # Export Error file for later upload upon correction
            if errs.any?
                errFile ="errors_#{Date.today.strftime('%d%b%y')}.csv"
                errs.insert(0, Student.csv_header)
                errCSV = CSV.generate do |csv|
                    errs.each {|row| csv << row}
                end
                send_data errCSV,
                :type => 'text/csv; charset=iso-8859-1; header=present',
                :disposition => "attachment; filename=#{errFile}.csv"
                else
                flash[:notice] = I18n.t('Student import success')
                redirect_to :action => "index"
            end
        end
    end
 

  # GET /nfers/1/edit
  def edit
    @nfer = Nfer.find(params[:id])
  end

  # POST /nfers
  # POST /nfers.json
  def create
    @nfer = Nfer.new(params[:nfer])

    respond_to do |format|
      if @nfer.save
        format.html { redirect_to @nfer, notice: 'Nfer was successfully created.' }
        format.json { render json: @nfer, status: :created, location: @nfer }
      else
        format.html { render action: "new" }
        format.json { render json: @nfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nfers/1
  # PUT /nfers/1.json
  def update
    @nfer = Nfer.find(params[:id])

    respond_to do |format|
      if @nfer.update_attributes(params[:nfer])
        format.html { redirect_to @nfer, notice: 'Nfer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nfer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nfers/1
  # DELETE /nfers/1.json
  def destroy
    @nfer = Nfer.find(params[:id])
    @nfer.destroy

    respond_to do |format|
      format.html { redirect_to nfers_url }
      format.json { head :no_content }
    end
  end
  
  def clean_up
  	@nfers = Nfer.all
  	
  	#strip empty
  	@nfers.each do |n|
  		if n.raw.nil?
  			n.destroy
  		end
  	end
  	#link ids
  	@nfers.each do |n|
  		if n.student_id.nil?
	  		@s = Student.find(:first, :conditions => {:schoolreference => n.schoolreference})
  			n.update_attribute(:student_id, @s.id)
  		end
  	end
  	
  	
  
  end
end

app/helpers/nfe_rs_helper.rb
module NfeRsHelper
end

app/views/nfers/_form.html.erb
<%= simple_form_for(@nfer) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :subject %>
    <%= f.input :raw %>
    <%= f.input :ss %>
    <%= f.input :student_id %>
    <%= f.input :schoolreference %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nfers/clean_up.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @nfer.subject %>
</p>

<p>
  <b>Raw:</b>
  <%= @nfer.raw %>
</p>

<p>
  <b>Ss:</b>
  <%= @nfer.ss %>
</p>

<p>
  <b>Student:</b>
  <%= @nfer.student_id %>
</p>

<p>
  <b>Schoolreference:</b>
  <%= @nfer.schoolreference %>
</p>
<p>
<b>Date-taken</b>
  <%= @nfer.date_taken %>
</p>


<%= link_to 'Edit', edit_nfer_path(@nfer) %> |
<%= link_to 'Back', nfers_path %>

app/views/nfers/edit.html.erb
<h1>Editing nfer</h1>

<%= render 'form' %>

<%= link_to 'Show', @nfer %> |
<%= link_to 'Back', nfers_path %>

app/views/nfers/index.html.erb
<h1>Listing nfers</h1>


<table>
  <tr>
    <th>Subject</th>
    <th>Raw</th>
    <th>Ss</th>
    <th>Student</th>
    <th>Schoolreference</th>
    <th>Date Taken</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nfers.each do |nfer| %>
  <tr>
    <td><%= nfer.subject %></td>
    <td><%= nfer.raw %></td>
    <td><%= nfer.ss %></td>
    <td><%= nfer.student_id %></td>
    <td><%= nfer.schoolreference %></td>
    <td><%= nfer.date_taken %></td>
    <td><%= link_to 'Show', nfer %></td>
    <td><%= link_to 'Edit', edit_nfer_path(nfer) %></td>
    <td><%= link_to 'Destroy', nfer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Nfer', new_nfer_path %>

app/views/nfers/new.html.erb
<h1>New nfer</h1>

<%= render 'form' %>

<%= link_to 'Back', nfers_path %>

<div style="clear:both;">
<br><br>
<h3>Bulk Add</h3>
<i>CSV file should be e.g </i>"Subject, Raw, Stand, StudentRef, date_taken"
<br>
<%= form_tag import_nfers_url, :multipart => true do %>
<%= file_field_tag "file" %>
<%= submit_tag "Upload and do your worst ..."%>
<% end %>
</div>

app/views/nfers/show.html.erb
<%= @nfers.size %> cleaned


<%= link_to 'Back', nfers_path %>